---
#
# Ansible managed
#
repository:
  description: Install and configure fips on your system.
  homepage: https://robertdebock.nl/
  topics: fips, infrastructure, linux, security, system, ansible, molecule, playbook
